### ISSUE TITLE
skeleton

### ISSUE THREAD

**Issue by dannyseiner** [UUBoys/youcube-fe#3]

**Comment by dannyseiner** [comment]
- REACT
- NEXT.JS
- TYPESCRIPT
- TAILWIND
- NEXT AUTH

@portak1 @M-Shella

**Comment by portak1** [comment]
Jo, tohle bude skeleton. To ostatní jsou postranní věci, ty tam uvádět nemusíš. Ty se doplní kdyžtak v dokumentaci.
